source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JLChatViewController_Example', :exclusive => true do
  pod "JLChatViewController", :path => "../"
end

target 'JLChatViewController_Tests', :exclusive => true do
  pod "JLChatViewController", :path => "../"

  
end
